# Generated by Django 5.2.6 on 2025-09-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='权益名称')),
                ('benefits_icon', models.TextField(blank=True, null=True, verbose_name='权益图标链接')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_benefits',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('api_id', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('base_url', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_payment_settings',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='支付名称')),
                ('amount', models.FloatField(blank=True, default=0, null=True, verbose_name='充值原价金额')),
                ('pay_price', models.FloatField(blank=True, default=0, null=True, verbose_name='支付折扣金额')),
                ('pay_channel', models.CharField(blank=True, choices=[('vip', 'VIP购买'), ('gold', '金币购买'), ('content', '内容购买'), ('goods', '商品购买')], max_length=255, null=True, verbose_name='支付渠道对应 vip gold')),
                ('days_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='充值天数')),
                ('gold_coin', models.IntegerField(blank=True, default=0, null=True, verbose_name='金币数量')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('promotion_text', models.TextField(blank=True, null=True, verbose_name='促销文案')),
                ('benefits', models.ManyToManyField(blank=True, related_name='payments', to='payments.benefits', verbose_name='会员权益')),
            ],
            options={
                'db_table': 't_payment',
                'ordering': ['create_time'],
            },
        ),
    ]
