# Generated by Django 5.2.6 on 2025-09-28 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_user_id_remove_order_user_nickname_and_more'),
        ('payments', '0002_remove_payment_user_id_remove_payment_user_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments_order', to='orders.order'),
            preserve_default=False,
        ),
    ]
