# Generated by Django 5.2.6 on 2025-09-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='daysnum',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='充值天数'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='充值金额'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_channel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='支付渠道对应 vip gold'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='支付方式'),
        ),
    ]
