# Generated by Django 5.2.6 on 2025-09-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_payment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='daysnum',
            new_name='days_num',
        ),
        migrations.AddField(
            model_name='payment',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
