# Generated by Django 5.2.6 on 2025-09-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_rename_daysnum_payment_days_num_payment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='base_url',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='pay_method',
        ),
        migrations.AddField(
            model_name='payment',
            name='gold_coin',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='金币数量'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否启用'),
        ),
    ]
