# Generated by Django 5.2.6 on 2025-09-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_remove_payment_api_id_remove_payment_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='充值金额'),
        ),
    ]
