# Generated by Django 5.2.6 on 2025-09-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='支付名称'),
        ),
    ]
