# Generated by Django 5.2.6 on 2025-09-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_pay_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
    ]
