# Generated by Django 5.2.6 on 2025-09-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_remove_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Membership_Benefits',
            field=models.TextField(blank=True, null=True, verbose_name='会员权益'),
        ),
    ]
