# Generated by Django 5.2.6 on 2025-09-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_payment_membership_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='支付金额'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='充值原价金额'),
        ),
    ]
