# Generated by Django 5.2.6 on 2025-09-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_payment_pay_price_alter_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Membership_Benefits',
            new_name='membership_benefits',
        ),
        migrations.AddField(
            model_name='payment',
            name='promotion_text',
            field=models.TextField(blank=True, null=True, verbose_name='促销文案'),
        ),
    ]
