# Generated by Django 5.2.6 on 2025-09-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_rename_membership_benefits_payment_membership_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='支付折扣金额'),
        ),
    ]
