# Generated by Django 5.2.6 on 2025-09-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_alter_payment_pay_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='benefits_icon',
            field=models.TextField(blank=True, null=True, verbose_name='会员权益ico链接'),
        ),
    ]
