# Generated by Django 5.2.6 on 2025-09-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_payment_benefits_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='权益名称')),
                ('benefits_icon', models.TextField(blank=True, null=True, verbose_name='权益图标链接')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_benefits',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='benefits_icon',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='membership_benefits',
        ),
        migrations.AddField(
            model_name='payment',
            name='benefits',
            field=models.ManyToManyField(blank=True, related_name='payments', to='payments.benefits', verbose_name='会员权益'),
        ),
    ]
