# Generated by Django 5.2.6 on 2025-09-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_benefits_remove_payment_benefits_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_channel',
            field=models.CharField(blank=True, choices=[('normal', '普通用户'), ('vip', 'VIP用户'), ('svip', 'SVIP用户')], max_length=255, null=True, verbose_name='支付渠道对应 vip gold'),
        ),
    ]
