# Generated by Django 5.2.6 on 2025-09-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_alter_payment_pay_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_channel',
            field=models.CharField(blank=True, choices=[('vip', 'VIP购买'), ('gold', '金币购买'), ('content', '内容购买'), ('goods', '商品购买')], max_length=255, null=True, verbose_name='支付渠道对应 vip gold'),
        ),
    ]
