# Generated by Django 5.2.6 on 2025-09-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixed_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('short', '短视频'), ('long', '长视频')], max_length=255, null=True)),
                ('data', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_url', models.JSONField(blank=True, null=True)),
                ('tabs', models.CharField(blank=True, choices=[('follow', '关注'), ('latest', '最新'), ('recommend', '推荐'), ('cashback', '发现'), ('selected', '精选')], max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('review_status', models.CharField(blank=True, max_length=255, null=True)),
                ('view_count', models.IntegerField(blank=True, default=0, null=True)),
                ('like_count', models.IntegerField(blank=True, default=0, null=True)),
                ('comment_count', models.IntegerField(blank=True, default=0, null=True)),
                ('favorite_count', models.IntegerField(blank=True, default=0, null=True)),
                ('share_count', models.IntegerField(blank=True, default=0, null=True)),
                ('score_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='统计评分人数')),
                ('score_total', models.FloatField(blank=True, default=0, null=True, verbose_name='总评分')),
                ('downvote_total', models.IntegerField(blank=True, default=0, null=True)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('is_permanent', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('object_fit', models.CharField(blank=True, max_length=255, null=True)),
                ('fullScreenShow', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 't_content',
                'ordering': ['-create_time'],
            },
        ),
    ]
