# Generated by Django 5.2.6 on 2025-09-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_url', models.JSONField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('author_id', models.IntegerField(blank=True, null=True)),
                ('author_nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('author_avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('review_status', models.CharField(blank=True, max_length=255, null=True)),
                ('view_count', models.IntegerField(blank=True, default=0, null=True)),
                ('like_count', models.IntegerField(blank=True, default=0, null=True)),
                ('comment_count', models.IntegerField(blank=True, default=0, null=True)),
                ('favorite_count', models.IntegerField(blank=True, default=0, null=True)),
                ('share_count', models.IntegerField(blank=True, default=0, null=True)),
                ('score_count', models.IntegerField(blank=True, default=0, null=True)),
                ('score_total', models.IntegerField(blank=True, default=0, null=True)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('is_permanent', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_content',
                'ordering': ['create_time', 'title'],
            },
        ),
    ]
