# Generated by Django 5.2.6 on 2025-09-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='tags',
        ),
        migrations.AddField(
            model_name='content',
            name='tabs',
            field=models.CharField(blank=True, choices=[('follow', '关注'), ('latest', '最新'), ('recommend', '推荐'), ('cashback', '发现'), ('selected', '精选')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='category_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='标签id'),
        ),
        migrations.AlterField(
            model_name='content',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='标签name'),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(blank=True, choices=[('short', '短视频'), ('long', '长视频')], max_length=255, null=True),
        ),
    ]
