# Generated by Django 5.2.6 on 2025-09-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_remove_content_tags_content_tabs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-create_time']},
        ),
        migrations.AddField(
            model_name='content',
            name='fullScreenShow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='content',
            name='object_fit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
