# Generated by Django 5.2.6 on 2025-09-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='视频时长秒'),
        ),
    ]
