# Generated by Django 5.2.6 on 2025-09-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_content_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='视频时长，毫秒'),
        ),
    ]
