# Generated by Django 5.2.6 on 2025-09-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_content_options_content_fullscreenshow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='prefixed_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
