# Generated by Django 5.2.6 on 2025-10-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_content_author_content_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='content',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='经度'),
        ),
    ]
