# Generated by Django 5.2.6 on 2025-10-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_content_latitude_content_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='是否免费视频'),
        ),
    ]
