# Generated by Django 5.2.6 on 2025-09-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_content_prefixed_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='downvote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
