# Generated by Django 5.2.6 on 2025-09-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_content_downvote_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
