# Generated by Django 5.2.6 on 2025-09-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_content_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='rating_num',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
