# Generated by Django 5.2.6 on 2025-09-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_content_rating_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='rating_num',
        ),
        migrations.AlterField(
            model_name='content',
            name='score_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='统计评分人数'),
        ),
        migrations.AlterField(
            model_name='content',
            name='score_total',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='总评分'),
        ),
    ]
