# Generated by Django 5.2.6 on 2025-09-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('contents', '0008_remove_content_rating_num_alter_content_score_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='content',
            name='category_name',
        ),
        migrations.AddField(
            model_name='content',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='contents', to='categories.category', verbose_name='标签name'),
        ),
    ]
