# Generated by Django 5.2.6 on 2025-09-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_remove_content_category_id_and_more'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='categories',
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contents', to='tags.tag', verbose_name='标签'),
        ),
    ]
