services:
  web:
    build: .
    container_name: flashc_web
    command: sh -c "
      find . -path \"*/migrations/*.py\" -not -name \"__init__.py\" -delete &&
      find . -path \"*/migrations/*.pyc\" -delete &&
      python manage.py makemigrations &&
      python manage.py migrate --noinput && 
      python manage.py runserver 0.0.0.0:8000"
    ports:
        - "10080:8000"
    expose:
      - "8000"
    volumes:
      - ./staticfiles:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=FlashCircle.settings
      - ALLOWED_HOSTS=*
      - POSTGRES_HOST=db
      - POSTGRES_DB=flashc
      - POSTGRES_USER=flashc
      - POSTGRES_PASSWORD=flashc
      - POSTGRES_PORT=5432
    depends_on:
      - db
    networks:
      - flashc_net

  db:
    image: postgres:16-alpine
    container_name: flahcicle_db
    environment:
      - POSTGRES_DB=flashc
      - POSTGRES_USER=flashc
      - POSTGRES_PASSWORD=flashc
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - flashc_net

volumes:
  pgdata:


networks:
  flashc_net:
    name: flashc_net

