# Generated by Django 5.2.6 on 2025-09-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_nickname', models.IntegerField(blank=True, null=True)),
                ('target_title', models.CharField(blank=True, max_length=255, null=True)),
                ('target_cover', models.CharField(blank=True, max_length=255, null=True)),
                ('target_author_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_favorite',
                'ordering': ['create_time'],
            },
        ),
    ]
