# Generated by Django 5.2.6 on 2025-09-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='status',
            field=models.CharField(choices=[('active', '已收藏'), ('inactive', '已取消')], default='active', max_length=20),
        ),
    ]
