# Generated by Django 5.2.6 on 2025-09-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0002_alter_favorite_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user_nickname',
            field=models.CharField(blank=True, null=True),
        ),
    ]
