# Generated by Django 5.2.6 on 2025-09-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0003_alter_favorite_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='type',
            field=models.CharField(blank=True, choices=[('dynamic', '动态'), ('content', '内容')], max_length=255, null=True),
        ),
    ]
