# Generated by Django 5.2.6 on 2025-09-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0004_alter_favorite_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('dynamic', '动态'), ('content', '内容')], max_length=255, null=True)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_nickname', models.CharField(blank=True, null=True)),
                ('target_title', models.CharField(blank=True, max_length=255, null=True)),
                ('target_cover', models.CharField(blank=True, max_length=255, null=True)),
                ('target_author_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', '已点踩'), ('inactive', '已取消')], default='active', max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_downvote',
                'ordering': ['create_time'],
                'unique_together': {('type', 'target_id', 'user_id')},
            },
        ),
    ]
