# Generated by Django 5.2.7 on 2025-10-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixed_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('tabs', models.CharField(blank=True, choices=[('follow', '关注'), ('latest', '最新'), ('recommend', '推荐'), ('cashback', '发现'), ('selected', '精选')], max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('video', '视频'), ('dynamic', '动态')], max_length=255, null=True)),
                ('images', models.JSONField(blank=True, help_text="图片URL数组，例如: ['url1', 'url2']", null=True)),
                ('video_url', models.JSONField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('is_vip', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('favorite_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(blank=True, default=0, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='经度')),
                ('categories', models.ManyToManyField(blank=True, related_name='dynamics', to='categories.category', verbose_name='标签')),
            ],
            options={
                'db_table': 't_social_dynamic',
                'ordering': ['-create_time'],
            },
        ),
    ]
