# Generated by Django 5.2.6 on 2025-09-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('video_url', models.JSONField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('is_vip', models.BooleanField(default=True)),
                ('price', models.IntegerField(default=0)),
                ('user_id', models.IntegerField()),
                ('user_nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('user_avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_social_dynamic',
                'ordering': ['create_time'],
            },
        ),
    ]
