# Generated by Django 5.2.6 on 2025-09-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamic',
            name='images',
            field=models.JSONField(blank=True, help_text="图片URL数组，例如: ['url1', 'url2']", null=True),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='type',
            field=models.CharField(blank=True, choices=[('video', '视频'), ('dynamic', '动态')], max_length=255, null=True),
        ),
    ]
