# Generated by Django 5.2.6 on 2025-09-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0002_alter_dynamic_images_alter_dynamic_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamic',
            options={'ordering': ['-create_time']},
        ),
        migrations.AddField(
            model_name='dynamic',
            name='tabs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
