# Generated by Django 5.2.6 on 2025-09-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0003_alter_dynamic_options_dynamic_tabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
    ]
