# Generated by Django 5.2.6 on 2025-10-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0003_dynamic_latitude_dynamic_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamic',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格'),
        ),
    ]
