# Generated by Django 5.2.6 on 2025-09-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0004_dynamic_favorite_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
    ]
