# Generated by Django 5.2.6 on 2025-10-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_categories_type'),
        ('societies', '0004_alter_dynamic_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='dynamics', to='categories.category', verbose_name='标签'),
        ),
    ]
