# Generated by Django 5.2.6 on 2025-09-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0005_dynamic_followers_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamic',
            name='followers_count',
        ),
    ]
