# Generated by Django 5.2.6 on 2025-09-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0007_alter_dynamic_tabs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamic',
            name='tabs',
            field=models.CharField(blank=True, choices=[('follow', '关注'), ('latest', '最新'), ('recommend', '推荐'), ('cashback', '返现'), ('selected', '发现')], max_length=255, null=True),
        ),
    ]
