# Generated by Django 5.2.6 on 2025-09-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0009_alter_dynamic_tabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
