# Generated by Django 5.2.6 on 2025-09-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0010_dynamic_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='prefixed_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
