# Generated by Django 5.2.6 on 2025-09-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.IntegerField(blank=True, null=True)),
                ('followee_id', models.IntegerField(blank=True, null=True)),
                ('follower_nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('follower_avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('followee_nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('followee_avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_follow',
                'ordering': ['create_time'],
            },
        ),
    ]
