# Generated by Django 5.2.6 on 2025-09-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='status',
            field=models.CharField(choices=[('active', '已关注'), ('inactive', '已取消')], default='active', max_length=20),
        ),
    ]
