# Generated by Django 5.2.6 on 2025-09-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0002_alter_follow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followee_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='关注了谁'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='自己'),
        ),
    ]
