# Generated by Django 5.2.6 on 2025-09-30 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(choices=[(1.0, '1分'), (1.5, '1.5分'), (2.0, '2分'), (2.5, '2.5分'), (3.0, '3分'), (3.5, '3.5分'), (4.0, '4分'), (4.5, '4.5分'), (5.0, '5分')])),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='contents.content')),
            ],
            options={
                'db_table': 't_rating',
                'ordering': ['-create_time'],
            },
        ),
    ]
