# Generated by Django 5.2.6 on 2025-09-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('parent_comment_id', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('user_avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('reply_to_user_id', models.IntegerField(blank=True, null=True)),
                ('reply_to_user_nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('reply_to_user_avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('like_count', models.IntegerField(blank=True, default=0, null=True)),
                ('reply_count', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_comment',
                'ordering': ['create_time'],
            },
        ),
    ]
