# Generated by Django 5.2.6 on 2025-09-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tabs',
            field=models.CharField(blank=True, choices=[('latest', '最新'), ('recommend', '推荐')], max_length=255, null=True),
        ),
    ]
