# Generated by Django 5.2.6 on 2025-09-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField(blank=True, null=True)),
                ('receiver_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='房间号ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('video', '视频'), ('audio', '音频'), ('file', '文件'), ('system', '系统消息')], default='text', max_length=255)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('reply_to_id', models.IntegerField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_message',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('allow_stranger_msg', models.BooleanField(default=False)),
                ('auto_read_receipt', models.BooleanField(default=False)),
                ('message_notification', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_message_setting',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户id')),
                ('other_user_id', models.IntegerField(blank=True, null=True)),
                ('session_id', models.CharField(max_length=255, unique=True, verbose_name='会话id')),
                ('session_type', models.CharField(choices=[('private', '私聊'), ('group', '群聊')], default='private', max_length=20)),
                ('last_message_id', models.IntegerField(blank=True, null=True)),
                ('last_message_time', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.IntegerField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_message_session',
                'ordering': ['-update_time'],
                'unique_together': {('user_id', 'session_id')},
            },
        ),
    ]
