# Generated by Django 5.2.6 on 2025-09-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-update_time']},
        ),
        migrations.AddField(
            model_name='session',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='session_id',
            field=models.CharField(default=0, max_length=255, unique=True, verbose_name='会话id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('private', '私聊'), ('group', '群聊')], default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='房间ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', '文本'), ('image', '图片'), ('video', '视频'), ('audio', '音频'), ('file', '文件')], default='text', max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='用户id'),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('user_id', 'session_id')},
        ),
    ]
