# Generated by Django 5.2.6 on 2025-09-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_session_options_session_is_pinned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', '文本'), ('image', '图片'), ('video', '视频'), ('audio', '音频'), ('file', '文件'), ('system', '系统消息')], default='text', max_length=255),
        ),
    ]
