# Generated by Django 5.2.6 on 2025-09-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='房间ID'),
        ),
    ]
