# Generated by Django 5.2.6 on 2025-09-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_receiver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='房间号ID'),
        ),
    ]
