# Generated by Django 5.2.6 on 2025-09-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('click_url', models.CharField(blank=True, max_length=255, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('target_type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('sort_order', models.IntegerField(blank=True, default=0, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('is_vip', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 't_ad',
                'ordering': ['create_time', 'name'],
            },
        ),
    ]
