# Generated by Django 5.2.7 on 2025-10-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='banner_game_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='游戏截图图片'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='game_tags',
            field=models.ManyToManyField(blank=True, related_name='ad', to='tags.tag', verbose_name='兴趣标签'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='封面'),
        ),
    ]
