# Generated by Django 5.2.7 on 2025-10-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_advertisement_banner_game_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.IntegerField(blank=True, default=0, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 't_carousel',
            },
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='banner_game_url',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='banner_game',
            field=models.ManyToManyField(blank=True, related_name='ad', to='advertisement.carousel', verbose_name='游戏截图（关联轮播图）'),
        ),
    ]
