# Generated by Django 5.2.7 on 2025-10-23 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_carousel_remove_advertisement_banner_game_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='banner_game',
        ),
        migrations.AddField(
            model_name='carousel',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='advertisement.advertisement', verbose_name='所属广告'),
        ),
    ]
