# Generated by Django 5.2.6 on 2025-09-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('dynamic', '动态'), ('content', '内容'), ('comment', '评论'), ('video', '视频')], default='dynamic', max_length=20)),
                ('target_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('user_nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('user_avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('target_author_id', models.IntegerField(blank=True, null=True)),
                ('target_title', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', '已点赞'), ('inactive', '已取消')], default='active', max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_like',
                'ordering': ['-create_time'],
                'unique_together': {('type', 'target_id', 'user_id')},
            },
        ),
    ]
