# Generated by Django 5.2.6 on 2025-09-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='type',
            field=models.CharField(choices=[('dynamic', '动态'), ('video', '视频')], default='dynamic', max_length=20),
        ),
    ]
