# Generated by Django 5.2.6 on 2025-09-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_alter_like_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-create_time']},
        ),
        migrations.AlterField(
            model_name='like',
            name='status',
            field=models.CharField(choices=[('active', '已点赞'), ('inactive', '已取消')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='like',
            name='target_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('type', 'target_id', 'user_id')},
        ),
    ]
