# Generated by Django 5.2.6 on 2025-09-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_alter_like_options_alter_like_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='type',
            field=models.CharField(choices=[('dynamic', '动态'), ('content', '内容'), ('comment', '评论'), ('video', '视频')], default='dynamic', max_length=20),
        ),
    ]
