# Generated by Django 5.2.6 on 2025-10-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categories_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
