# Generated by Django 5.2.6 on 2025-09-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '待领取'), ('claimed', '已领取'), ('completed', '已完成'), ('expired', '已过期')], default='pending', max_length=255)),
                ('claimed_time', models.DateTimeField(blank=True, null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_task_reward',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('daily', '每日任务'), ('checkin', '签到任务'), ('novice', '新手任务')], max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('data', models.JSONField(blank=True, null=True)),
                ('sort', models.IntegerField(default=0)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='任务图片URL')),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_task_template',
                'ordering': ['create_time'],
            },
        ),
    ]
