# Generated by Django 5.2.6 on 2025-09-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_reward_task_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='任务图片URL'),
        ),
    ]
