# Generated by Django 5.2.6 on 2025-10-28 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='配置名称', max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('azure_openai', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('custom', 'Custom')], help_text='厂商', max_length=32)),
                ('model', models.CharField(help_text='模型名称/版本', max_length=100)),
                ('enabled', models.BooleanField(default=True, help_text='是否启用')),
                ('is_default', models.BooleanField(default=False, help_text='是否设为默认（全局唯一）')),
                ('priority', models.IntegerField(default=0, help_text='优先级，数值越大优先')),
                ('api_key', models.CharField(help_text='访问密钥，读取时应掩码', max_length=256)),
                ('base_url', models.URLField(blank=True, help_text='自定义 API Base URL（代理/Azure 场景）')),
                ('region', models.CharField(blank=True, help_text='区域（Azure 等需要）', max_length=50)),
                ('api_version', models.CharField(blank=True, help_text='API 版本（Azure/OpenAI 兼容接口）', max_length=50)),
                ('organization_id', models.CharField(blank=True, help_text='组织/项目标识（可选）', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人（管理员）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_aiconfig',
                'ordering': ['-is_default', '-priority', 'name'],
            },
        ),
    ]
