# Generated by Django 5.2.6 on 2025-10-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member_level',
            field=models.CharField(choices=[('normal', '普通用户'), ('vip', 'VIP用户'), ('svip', 'SVIP用户'), ('robot', 'robot机器人用户')], default='normal', max_length=10),
        ),
    ]
