# Generated by Django 5.2.6 on 2025-09-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='user',
            name='followers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='粉丝数量'),
        ),
        migrations.AddField(
            model_name='user',
            name='following_count',
            field=models.PositiveIntegerField(default=0, verbose_name='关注数量'),
        ),
        migrations.AddField(
            model_name='user',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='获赞数量'),
        ),
    ]
