# Generated by Django 5.2.6 on 2025-09-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, null=True, verbose_name='头像URL'),
        ),
    ]
