# Generated by Django 5.2.6 on 2025-10-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vip_days',
        ),
    ]
