# Generated by Django 5.2.6 on 2025-10-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_member_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='running_state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='机器人执行状态'),
        ),
    ]
