# Generated by Django 5.2.6 on 2025-10-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_vip_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vip_days',
            field=models.DateTimeField(blank=True, null=True, verbose_name='会员到期时间'),
        ),
    ]
