# Generated by Django 5.2.6 on 2025-09-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gold_coin',
            field=models.PositiveIntegerField(default=0, verbose_name='金币数量'),
        ),
    ]
