# Generated by Django 5.2.6 on 2025-10-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_vip_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, null=True, verbose_name='头像URL'),
        ),
    ]
