# Generated by Django 5.2.6 on 2025-09-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_gold_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vip_days',
            field=models.PositiveIntegerField(default=0, verbose_name='会员天数'),
        ),
    ]
