# Generated by Django 5.2.6 on 2025-09-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_vip_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (1, '禁言'), (2, '冻结'), (3, '其他')], default=0, verbose_name='用户状态'),
        ),
    ]
