# Generated by Django 5.2.6 on 2025-09-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='user_bio',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='user_nickname',
        ),
    ]
