# Generated by Django 5.2.6 on 2025-10-21 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userpurchase'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpurchase',
            table='t_user_purchases',
        ),
    ]
