# Generated by Django 5.2.6 on 2025-09-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_user_nickname_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vip',
            field=models.BooleanField(default=True, verbose_name='用户是否为vip'),
        ),
    ]
