# Generated by Django 5.2.6 on 2025-10-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userpurchase_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpurchase',
            name='object_id',
            field=models.IntegerField(db_index=True, verbose_name='关联内容ID'),
        ),
    ]
