# Generated by Django 5.2.6 on 2025-09-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('user', '0007_user_is_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='users', to='categories.category', verbose_name='关注的分类'),
        ),
    ]
