# Generated by Django 5.2.6 on 2025-10-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userpurchase_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='用户是否为vip'),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='content_type',
            field=models.CharField(choices=[('content', '内容'), ('dynamic', '动态')], max_length=20, verbose_name='content,dynamic'),
        ),
    ]
