# Generated by Django 5.2.6 on 2025-09-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('user', '0008_user_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='categories',
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='users', to='tags.tag', verbose_name='兴趣标签'),
        ),
    ]
