# Generated by Django 5.2.6 on 2025-09-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_id', models.IntegerField(blank=True, null=True)),
                ('goods_name', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_type', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_cover', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('coin_amount', models.IntegerField(blank=True, null=True)),
                ('content_id', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('payment_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('cash_amount', models.IntegerField(blank=True, null=True)),
                ('coin_cost', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('discount_amount', models.IntegerField(blank=True, null=True)),
                ('final_amount', models.IntegerField(blank=True, null=True)),
                ('pay_status', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_method', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 't_order',
                'ordering': ['create_time'],
            },
        ),
    ]
