# Generated by Django 5.2.6 on 2025-09-30 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('cash_amount', models.IntegerField(blank=True, null=True)),
                ('final_amount', models.IntegerField(blank=True, null=True)),
                ('pay_status', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_method', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('trade_no', models.CharField(blank=True, max_length=255, null=True)),
                ('merc_id', models.CharField(blank=True, max_length=255, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('player_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(blank=True, max_length=255, null=True)),
                ('player_name', models.CharField(blank=True, max_length=255, null=True)),
                ('player_tel', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_account', models.CharField(blank=True, max_length=255, null=True)),
                ('notify_url', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_money', models.IntegerField(blank=True, null=True)),
                ('notify_status', models.CharField(blank=True, max_length=255, null=True)),
                ('oid', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_good', to='goods.good')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='payments.payment')),
            ],
            options={
                'db_table': 't_order',
                'ordering': ['create_time'],
            },
        ),
    ]
