# Generated by Django 5.2.6 on 2025-10-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_channel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
