# Generated by Django 5.2.6 on 2025-09-29 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_device_id_order_device_type_order_merc_id_and_more'),
        ('payments', '0019_alter_payment_pay_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='payments.payment'),
            preserve_default=False,
        ),
    ]
