# Generated by Django 5.2.6 on 2025-09-29 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('orders', '0004_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='goods_category_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='goods_cover',
        ),
        migrations.RemoveField(
            model_name='order',
            name='goods_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='goods_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='goods_type',
        ),
        migrations.AddField(
            model_name='order',
            name='good',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_good', to='goods.good'),
            preserve_default=False,
        ),
    ]
