# Generated by Django 5.2.6 on 2025-09-29 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('orders', '0005_remove_order_goods_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_good', to='goods.good'),
        ),
    ]
