# Generated by Django 5.2.6 on 2025-09-30 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coin_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coin_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='content_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
